name: weather_app
description: "A weather application with Firebase authentication and OpenWeatherMap API integration"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.32.0
  firebase_auth: ^4.18.0
  google_sign_in: ^6.1.5
  cloud_firestore: ^4.3.1
  http: ^0.13.5
  intl: ^0.18.1
  flutter_spinkit: ^5.1.0
  shimmer: ^3.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  mocktail: ^0.3.0
  http_mock_adapter: ^0.6.1 # Updated to latest stable version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/weather_icon.png"
  adaptive_icon_background: "#2A79C7"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_logo.png
