// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJl8RfzEVKc45PdZrbaJ1iw_IVccUc5T0',
    appId: '1:872622520259:web:0ef54324f0cbc68cefaf76',
    messagingSenderId: '872622520259',
    projectId: 'weather-9f4ba',
    authDomain: 'weather-9f4ba.firebaseapp.com',
    storageBucket: 'weather-9f4ba.firebasestorage.app',
    measurementId: 'G-W2HZ1Z67RG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbbt0WiE6j-8lDwrFoniptlkouxj0vds',
    appId: '1:872622520259:android:68b76a39dfe420ddefaf76',
    messagingSenderId: '872622520259',
    projectId: 'weather-9f4ba',
    storageBucket: 'weather-9f4ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xQBNetSSioupZLHMoQFAjfx7OdezCsY',
    appId: '1:872622520259:ios:41aaffd3519ba202efaf76',
    messagingSenderId: '872622520259',
    projectId: 'weather-9f4ba',
    storageBucket: 'weather-9f4ba.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6xQBNetSSioupZLHMoQFAjfx7OdezCsY',
    appId: '1:872622520259:ios:41aaffd3519ba202efaf76',
    messagingSenderId: '872622520259',
    projectId: 'weather-9f4ba',
    storageBucket: 'weather-9f4ba.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJl8RfzEVKc45PdZrbaJ1iw_IVccUc5T0',
    appId: '1:872622520259:web:e21e46f698bc8281efaf76',
    messagingSenderId: '872622520259',
    projectId: 'weather-9f4ba',
    authDomain: 'weather-9f4ba.firebaseapp.com',
    storageBucket: 'weather-9f4ba.firebasestorage.app',
    measurementId: 'G-Y7MNG8LMWP',
  );
}
